# Generated by Django 3.2.25 on 2024-03-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expert_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('place', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('proof', models.FileField(upload_to='')),
                ('DOB', models.DateField()),
                ('experience', models.IntegerField()),
                ('phone_no', models.BigIntegerField()),
                ('mail_id', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='parent_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('mail_id', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Tips_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.TextField()),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.expert_table')),
            ],
        ),
        migrations.CreateModel(
            name='study_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('discription', models.TextField()),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
        migrations.CreateModel(
            name='guidance_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guidance', models.TextField()),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.expert_table')),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
        migrations.AddField(
            model_name='expert_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.login_table'),
        ),
        migrations.CreateModel(
            name='doubt_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.TextField()),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.expert_table')),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.expert_table')),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
        migrations.CreateModel(
            name='child_assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=100)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.expert_table')),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
    ]
