# Generated by Django 3.2.25 on 2024-03-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.TextField()),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.expert_table')),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
    ]
