# Generated by Django 3.2.25 on 2024-03-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASD', '0002_assign_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='EXPERT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ASD.expert_table'),
            preserve_default=False,
        ),
    ]
