# Generated by Django 3.2.25 on 2024-04-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASD', '0003_study_material_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_table',
            name='EXPERT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ASD.expert_table'),
            preserve_default=False,
        ),
    ]
