# Generated by Django 3.2.25 on 2024-04-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASD', '0004_feedback_table_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
    ]
