# Generated by Django 3.2.25 on 2024-04-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASD', '0005_question_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatbot_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
    ]
