# Generated by Django 3.2.25 on 2024-04-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASD', '0006_chatbot_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_frame_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=100)),
                ('ratio', models.FloatField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASD.parent_table')),
            ],
        ),
    ]
