# Generated by Django 3.2.25 on 2024-04-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASD', '0007_video_frame_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_table',
            name='answer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
