# Generated by Django 3.2.25 on 2024-04-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASD', '0010_question_result_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatbot_table',
        ),
    ]
